
const teamData = [
  {
    "key" : 0,
    "name" : "Atlanta Hawks",
    "conference" : "E",
    "logo" : require("./teamLogos/Hawks.png"),
  },
  {
    "key" : "1",
    "name" : "Boston Celtics",
    "conference" : "E",
    "logo" : require("./teamLogos/Celtics.png"),
  },
   {
    "key" : "2",
    "name" : "Brookly Nets",
    "conference" : "E",
    "logo" : require("./teamLogos/Nets.png"),
  },
   {
    "key" : "3",
    "name" : "Charlotte Hornets",
    "conference" : "E",
    "logo" : require("./teamLogos/Hornets.png"),
  },
   {
    "key" : "4",
    "name" : "Chicago Bulls",
    "conference" : "E",
    "logo" : require("./teamLogos/Bulls.png"),
  },
   {
    "key" : "5",
    "name" : "Cleveland Cavaliers",
    "conference" : "E",
    "logo" : require("./teamLogos/Cavaliers.png"),
  },
   {
    "key" : "6",
    "name" : "Dallas Mavericks",
    "conference" : "W",
    "logo" : require("./teamLogos/Mavericks.png"),
  },
   {
    "key" : "7",
    "name" : "Denver Nuggets",
    "conference" : "W",
    "logo" : require("./teamLogos/Nuggets.png"),
  },
   {
    "key" : "8",
    "name" : "Detroit Pistons",
    "conference" : "E",
    "logo" : require("./teamLogos/Pistons.png"),
  },
   {
    "key" : "9",
    "name" : "Golden State Warriors",
    "conference" : "W",
    "logo" : require("./teamLogos/Warriors.png"),
  },
   {
    "key" : "10",
    "name" : "Houston Rockets",
    "conference" : "W",
    "logo" : require("./teamLogos/Rockets.png"),
  },
   {
    "key" : "11",
    "name" : "Indiana Pacers",
    "conference" : "E",
    "logo" : require("./teamLogos/Pacers.png"),
  },
   {
    "key" : "12",
    "name" : "Los Angeles Clippers",
    "conference" : "W",
    "logo" : require("./teamLogos/Clippers.png"),
  },
   {
    "key" : "13",
    "name" : "Los Angeles Lakers",
    "conference" : "W",
    "logo" : require("./teamLogos/Lakers.png"),
  },
   {
    "key" : "14",
    "name" : "Memphis Grizzlies",
    "conference" : "W",
    "logo" : require("./teamLogos/Grizzlies.png"),
  },
   {
    "key" : "15",
    "name" : "Miami Heat",
    "conference" : "E",
    "logo" : require("./teamLogos/Heat.png"),
  },
   {
    "key" : "16",
    "name" : "Milwaukee Bucks",
    "conference" : "E",
    "logo" : require("./teamLogos/Bucks.png"),
  },
   {
    "key" : "17",
    "name" : "Minnesota Timberwolves",
    "conference" : "W",
    "logo" : require("./teamLogos/Timberwolves.png"),
  },
   {
    "key" : "18",
    "name" : "New Orleans Pelicans",
    "conference" : "W",
    "logo" : require("./teamLogos/Pelicans.png"),
  },
   {
    "key" : "19",
    "name" : "New York Knicks",
    "conference" : "E",
    "logo" : require("./teamLogos/Knicks.png"),
  },
   {
    "key" : "20",
    "name" : "Oklahoma City Thunder",
    "conference" : "W",
    "logo" : require("./teamLogos/Thunder.png"),
  },
   {
    "key" : "21",
    "name" : "Orlando Magic",
    "conference" : "E",
    "logo" : require("./teamLogos/Magic.png"),
  },
   {
    "key" : "22",
    "name" : "Philadelphia 76ers",
    "conference" : "E",
    "logo" : require("./teamLogos/76ers.png"),
  },
   {
    "key" : "23",
    "name" : "Phoenix Suns",
    "conference" : "W",
    "logo" : require("./teamLogos/Suns.png"),
  },
   {
    "key" : "24",
    "name" : "Portland Trail Blazers",
    "conference" : "W",
    "logo" : require("./teamLogos/Trail Blazers.png"),
  },
   {
    "key" : "25",
    "name" : "Sacramento Kings",
    "conference" : "W",
    "logo" : require("./teamLogos/Kings.png"),
  },
   {
    "key" : "26",
    "name" : "San Antonio Spurs",
    "conference" : "W",
    "logo" : require("./teamLogos/Spurs.png"),
  },
   {
    "key" : "27",
    "name" : "Toronto Raptors",
    "conference" : "E",
    "logo" : require("./teamLogos/Raptors.png"),
  },
   {
    "key" : "28",
    "name" : "Utah Jazz",
    "conference" : "W",
    "logo" : require("./teamLogos/Jazz.png"),
  },
   {
    "key" : "29",
    "name" : "Washington Wizards",
    "conference" : "E",
    "logo" : require("./teamLogos/Wizards.png"),
  },
]
module.exports = teamData;